Python 中列表的元素类型可以是任意类型，列表需要保存每个元素的指针；

NumPy 数组 `ndarray` 的元素只能是同一种类型，数值运算通常在同一种类型的数据之间进行；

*张量*（tensor）是矩阵在任意维度上的推广；张量的维度通常称为*轴*（axis）；
- 0D 张量就是一个数字，一维数组也称为 1D 张量，二维数组是 2D 张量，以此类推；

In [3]:
import numpy as np

print('NumPy version:', np.__version__)

NumPy version: 1.23.5


## 构造数组

### 用 `array()` 方法生成 NumPy 数组

In [19]:
data = [6, 8.5, 9, 0]
arr = np.array(data)
# dtype 是数组元素的类型
print(arr, type(arr), arr.dtype)
arr = arr.astype(np.int32)
print(arr, arr.dtype)

data_2d = [[1, 2, 3], [4, 5, 6]]
arr_2d = np.array(data_2d)
print(arr_2d, arr_2d.dtype)

[6.  8.5 9.  0. ] <class 'numpy.ndarray'> float64
[6 8 9 0] int32
[[1 2 3]
 [4 5 6]] int64


### 用 `arange()`，`linspace()` 生成 NumPy 数组

In [27]:
arr3 = np.arange(4)
print(arr3, type(arr3))
arr3 += 3
print(arr3)

arr4 = range(4)
print(arr4, type(arr4))

arr4 = np.linspace(1, 10, 8)
print(arr4)

[0 1 2 3] <class 'numpy.ndarray'>
[3 4 5 6]
range(0, 4) <class 'range'>
[ 1.          2.28571429  3.57142857  4.85714286  6.14285714  7.42857143
  8.71428571 10.        ]


### 填充数组

In [36]:
zeros = np.zeros((3, 4))
zeros = np.zeros(shape = (3, 4))
zeros = np.zeros(shape = [3, 4])
print(zeros)
# zeros_like()

arr5 = np.arange(6)
arr5 = arr5.reshape((2, 3))
print(arr5)
print(np.ones_like(arr5))
# ones()

# empty_like(), full_like()

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0 1 2]
 [3 4 5]]
[[1 1 1]
 [1 1 1]]


## 数组属性


In [48]:
import numpy as np

arr_1d = np.arange(1, 5, 0.5)
print(arr_1d, '\ndimension:', arr_1d.ndim, 'shape:', arr_1d.shape)

arr_2d = np.arange(15).reshape(3, 5)
print(arr_2d, '\ndimension:', arr_2d.ndim, 'shape:', arr_2d.shape)

arr_3d = np.arange(30).reshape(2, 3, 5)
print(arr_3d, '\ndimension:', arr_3d.ndim, 'shape:', arr_3d.shape)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5] 
dimension: 1 shape: (8,)
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 
dimension: 2 shape: (3, 5)
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]] 
dimension: 3 shape: (2, 3, 5)


## 数组运算

### 向量运算

*向量*：把一组数字排成一行（行向量）或一列（列向量）；
- 列向量对于向量坐标变换、空间映射而言更方便，因而一般都用列的形式表示向量；

In [81]:
# 普通做法
list1 = [1, 2, 3, 4]
list2 = [11, 12, 13, 14]
list3 = [ele1 + ele2 for ele1, ele2 in zip(list1, list2)]
print(list3)

# NumPy
list1_arr = np.array(list1)
list2_arr = np.array(list2)
print(list1_arr + list2_arr)

[12, 14, 16, 18]
[12 14 16 18]


### 算数运算

数组的 shape 相同，就能进行加、减、乘、除、取余、指数等运算；运算逐个元素进行；

In [59]:
# 中位数
# np.median?

# 方差
# np.var?

# 加权平均
# np.average?

# 算数平均
# np.mean?

### 逐元素运算与张量的点乘运算

NumPy 中的数组（或张量）运算基于基础线性代数子程序集（Basic Linear Algebra Subprograms，BLAS）实现；

BLAS 是一个更底层的高度并行的经过优化的张量操作程序，通常用 Fortran、C 编写；

In [79]:
# 逐元素
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.full((2, 2), 2)
print(arr1 * arr2)
print(np.multiply(arr1, arr2))

# 点乘
arr3 = np.arange(9).reshape(3, 3)
# 第一个矩阵的列数与第二个矩阵的行数相等
arr4 = np.ones((3, 2))
print('\n', arr3, '\n\n', arr4, '\n')
# @ 等价于 np.dot()
print(np.dot(arr3, arr4), '\n\n', arr3@arr4)

# 先转成矩阵后再直接乘
print('\n', np.mat(arr3) * np.mat(arr4))

mat33 = np.mat(np.random.random((3, 3)))
# 逆矩阵
mat33.I
# 转置矩阵
mat33.T
# 对应的二维数组
mat33.A

[[2 4]
 [6 8]]
[[2 4]
 [6 8]]

 [[0 1 2]
 [3 4 5]
 [6 7 8]] 

 [[1. 1.]
 [1. 1.]
 [1. 1.]] 

[[ 3.  3.]
 [12. 12.]
 [21. 21.]] 

 [[ 3.  3.]
 [12. 12.]
 [21. 21.]]

 [[ 3.  3.]
 [12. 12.]
 [21. 21.]]


array([[0.21838395, 0.30239568, 0.72797182],
       [0.6692076 , 0.83616157, 0.46729998],
       [0.51419869, 0.59233426, 0.49675784]])

## 爱因斯坦求和约定 Einstein Summation Convention

向量点乘公式：$s = \sum\limits_iv_iw_i$
- 包含 $i$ 个元素的一维数组和每维只有一个元素的 $i$ 维数组相乘；

爱因斯坦求和公式：$s = v_iw^i$
- 下标表示行向量中的元素，上标表示列向量中的元素；

矩阵 $A$ 的第 $m$ 行第 $n$ 列标记为 $A_n^m$；非爱因斯坦标记法则是 $A_{mn}$；

内积：
- 参与内积运算的两个向量维数必须相等，运算规则是将对应位置的元素相乘，然后相加合并，最终运算结果是一个标量；
